name: main_work
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  image_size_getter: ^2.1.3
  image_size_getter_http_input: ^2.0.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.4
  neopop: ^1.0.2
  firebase_auth: ^4.19.4
  lottie: ^3.1.0
  google_maps_flutter: ^2.6.1
  flutter_rating_bar: ^4.0.1
  location: ^6.0.2
  get_it: ^7.7.0
  redacted: ^1.0.11
  timelines: ^0.1.0
  go_router: ^14.2.7
  flutter_stripe: ^11.0.0
  flutter_stripe_web: 
  dio: ^5.5.0+1
  js: ^0.6.7
  order_tracker_zen: ^1.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon.png
  branding_bottom_padding: 24
  color_dark: "#121212"
  image_dark: assets/icon/icon.png

  android_12:
    image: assets/icon/icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/icon/icon.png
    icon_background_color_dark: "#121212"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon.png
    - assets/login.json
    - assets/welcome.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
