// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-D1gTkV-iJ1xQ9hRD3QaV1sI1fVgtlDI',
    appId: '1:591572251211:web:d95e049ea64264f6a793ce',
    messagingSenderId: '591572251211',
    projectId: 'store-845d3',
    authDomain: 'store-845d3.firebaseapp.com',
    storageBucket: 'store-845d3.appspot.com',
    measurementId: 'G-J9R0SFBFNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0lG0teyLfSs5JCWUoJeFtTB-_Fo8c28w',
    appId: '1:591572251211:android:282b11497818d046a793ce',
    messagingSenderId: '591572251211',
    projectId: 'store-845d3',
    storageBucket: 'store-845d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRvD_HZjKsxZvI8Cvu2FJF5FBhPecQYM',
    appId: '1:591572251211:ios:81620b8587d37ee7a793ce',
    messagingSenderId: '591572251211',
    projectId: 'store-845d3',
    storageBucket: 'store-845d3.appspot.com',
    iosBundleId: 'com.example.mainWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsRvD_HZjKsxZvI8Cvu2FJF5FBhPecQYM',
    appId: '1:591572251211:ios:81620b8587d37ee7a793ce',
    messagingSenderId: '591572251211',
    projectId: 'store-845d3',
    storageBucket: 'store-845d3.appspot.com',
    iosBundleId: 'com.example.mainWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-D1gTkV-iJ1xQ9hRD3QaV1sI1fVgtlDI',
    appId: '1:591572251211:web:aee5ac0bbc71fd0ba793ce',
    messagingSenderId: '591572251211',
    projectId: 'store-845d3',
    authDomain: 'store-845d3.firebaseapp.com',
    storageBucket: 'store-845d3.appspot.com',
    measurementId: 'G-DD226W7YG6',
  );
}
